app_name: benchmark_etl
meta:
  logging_level: INFO

# elt 01
extract:
  type: CSV_FILE_EXTRACTOR
  name: csv_read
  storage_backend: fs
  use_package: arrow
  path: E:\AcuityKP\Projects\airflow_etl_project\Airflow-ETL\data
  fail_no_files: false
  reprocess: true
  # read_mode: all
  filters:
    keep_latest: true
    include:
      - synthetic_100k

transformer:
  type: CHAIN_TRANSFORMER
  name: transChain
  transforms:
    - type: NO_OP_TRANSFORMER
      name: no_op

    - type: QUERY_TRANSFORMER
      name: query_transformer
      use_package: polars
      table_name: synthetic_100k
      query: >-
        SELECT
          *
        FROM
          synthetic_100k
        WHERE
          id % 5 = 0

storage:
  type: CSV_FILE_STORAGE
  name: csv_write
  storage_backend: fs
  use_package: arrow
  path: E:\AcuityKP\Projects\airflow_etl_project\Airflow-ETL\exports
  key: 'synthetic_100k_processed'
  time_fmt: '%Y-%m-%dT%H-%M-%S.%f%z'